### ISSUE TITLE
tracker: week ending Sep 25 2020

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/kubera-metal#1]
### Items
- [x] port relevant litmus portal code base to this repo - @AmitKumarDas 
- [ ] maya-agent that installs mayastor components - @amitbhatt818 
- [x] kubera-metal.yaml that installs kubera-metal components - @rohan2794 

### Next
- [ ] add DCO bot - @rohan2794 
- [ ] add golang linters - @rohan2794 
- [ ] add js linters - @rohan2794 
- [ ] add sh linters - @rohan2794 
- [ ] setup E2E via github actions - @amitbhatt818 
  - _note: run single node k8s on github action VM_
  - _note: this will run tests (i.e. assertions) on kubera-metal_
