### ISSUE TITLE
tracker: week ending Oct 2 2020 

### ISSUE THREAD

**Issue by AmitKumarDas** [mayadata-io/kubera-metal#6]
### Items
- [ ] kubera-metal workflow to install mayastor components - @AmitKumarDas  
- [ ] kubera-metal.yaml that installs kubera-metal components - @rohan2794 

### Next
- [ ] add DCO bot - @amitbhatt818 
- [ ] add golang linters - @amitbhatt818 
- [ ] add js linters - @amitbhatt818 
- [ ] add sh linters - @amitbhatt818
- [ ] add semantic release - @amitbhatt818  
- [ ] setup E2E via github actions - @amitbhatt818 
  - _note: run single node k8s on github action VM_
  - _note: this will run tests (i.e. assertions) on kubera-metal_
